# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    target-branch: "main"
    open-pull-requests-limit: 2 # Allow up globally to 2 simultaneously open pull requests for dependencies
    directory: "/server" # Location of package manifests
    commit-message:
      prefix: "server/dependabot"
    pull-request-branch-name:
      separator: "/"
    labels:
      - "dependencies"
      - "server"
    schedule:
      interval: "monthly"
    #  ignore:
      # Ignore all major updates for now until additional version ignores are working
      # Security updates are not affected by this ignore filter and still will be updated
    #  - dependency-name: "*"
    #    update-types: [ "version-update:semver-major" ]
  - package-ecosystem: "npm"
    open-pull-requests-limit: 2 # Allow up globally to 2 simultaneously open pull requests for dependencies
    target-branch: "main"
    directory: "/angular/"
    commit-message:
      prefix: "app/dependabot"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "angular"
    pull-request-branch-name:
      separator: "/"
    groups:
      dev-deps:
        dependency-type: "development"
      prod-deps:
        dependency-type: "production"