export * from './bubblePages/list/listBubbles.component'
export * from './bubblePages/detail/detailBubble.component'
export * from './humanPages/list/listHumans.component'
export * from './humanPages/detail/detailHuman.component'
export * from './humanPages/relations/relationsHuman.component'
