name: Build Angular

on:
  push:
    branches:
    - 'build/*'
    - 'feature/angular/*'
    - 'main'
  pull_request:
    branches:
    - 'main'

env:
  NODE_VERSION: 18.20.0
  NODE_OPTIONS: --max_old_space_size=4096

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm
        cache-dependency-path: angular/package-lock.json

    - name: Install root dependencies
      run: cd angular && npm ci

    - name: Build
      run: cd angular && npm run build:production
